TMS/Areas/Admin/Controllers/TMSController.cs
using Microsoft.AspNetCore.Mvc;
using TMS.Models;
using TMS.Data;
using Microsoft.AspNetCore.Authorization;
using TMS.Roles;

namespace TMS.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = TheRoles._Admin)]

    public class TMSController : Controller
    {
        public List<BooksDB> booksList = new List<BooksDB>();

        // DB + upload
        private readonly TMSDbContext _db;
        private readonly IWebHostEnvironment _hostEnvironment;

        public TMSController(TMSDbContext db, IWebHostEnvironment hostEnvironment)
        {
            _db = db;
            _hostEnvironment = hostEnvironment;
        }

        // Actions View       
        public IActionResult Manage()
        {
            booksList = _db.DbBooks.OrderBy(x => x.Title).ToList();
            return View(booksList);
        }

        public IActionResult AddBook(BooksDB addagain)
        {
            return View(addagain);
        }

        public IActionResult Edit(int id)
        {
            var foredit = _db.DbBooks.Find(id);
            return View(foredit);
        }


        //Actions Interact/Redirect
        [ValidateAntiForgeryToken]

        public IActionResult Adding(BooksDB adding, IFormFile img)
        {
            if (ModelState.IsValid /*&& adding.Genre1 != adding.Genre2*/)
            {
                //Add image
                string wwwRoot = _hostEnvironment.WebRootPath;

                string imgName = Path.GetFileNameWithoutExtension(img.FileName);
                var extension = Path.GetExtension(img.FileName);
                var upload = Path.Combine(wwwRoot, @"Images");

                using (var imgStreams = new FileStream(Path.Combine(upload, imgName + extension), FileMode.Create))
                {
                    img.CopyTo(imgStreams);
                }

                adding.Image = @"\Images\" + imgName + extension;
                ///////////

                _db.DbBooks.Add(adding);
                _db.SaveChanges();
                return RedirectToAction("Manage");
            }
            else
            {
                TempData["Mistake"] = "Make sure all the data is correct";
                return RedirectToAction("AddBook", adding);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Edit(BooksDB editing)
        {
            var check = ModelState["Price"];

            if (!check.Errors.Any())// && editing.Genre1 != editing.Genre2)
            {
                _db.DbBooks.Update(editing);
                _db.SaveChanges();
                return RedirectToAction("Manage");
            }
            else
            {
                TempData["Mistake"] = "Make sure all the data is correct";
                return RedirectToAction("Edit");
            }
        }

        [ValidateAntiForgeryToken]

        public IActionResult EditImage(int id, IFormFile img)
        {
            var imgedit = _db.DbBooks.Find(id);

            if (img != null)
            {
                var oldimg = Path.Combine(_hostEnvironment.WebRootPath, imgedit.Image.TrimStart('\\'));
                if (System.IO.File.Exists(oldimg))
                {
                    System.IO.File.Delete(oldimg);
                }

                string imgName = Path.GetFileNameWithoutExtension(img.FileName);
                var extension = Path.GetExtension(img.FileName);
                var upload = Path.Combine(_hostEnvironment.WebRootPath, @"Images");

                using (var imgStreams = new FileStream(Path.Combine(upload, imgName + extension), FileMode.Create))
                {
                    img.CopyTo(imgStreams);
                }

                imgedit.Image = @"\Images\" + imgName + extension;

                TempData["ImageUpload"] = "The image was succesfully changed";

                _db.DbBooks.Update(imgedit);
                _db.SaveChanges();
            }
            else
            {
                TempData["NoImage"] = "There is no image uploaded";
            }

            return RedirectToAction("Edit", new { id = imgedit.Id });
        }


        public IActionResult Delete(int id)
        {
            var todelete = _db.DbBooks.Find(id);

            System.IO.File.Delete(Path.Combine(_hostEnvironment.WebRootPath, todelete.Image.TrimStart('\\')));

            _db.DbBooks.Remove(todelete);
            _db.SaveChanges();
            return RedirectToAction("Manage");
        }
    }
}

TMS/Areas/Guest/Controllers/GuestViewsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TMS.Data;
using TMS.Models;

namespace TMS.Areas.Guest.Controllers
{
    [Area("Guest")]

    public class GuestViewsController : Controller
    {
        public List<BooksDB> booksList = new List<BooksDB>();

        //DB
        private readonly TMSDbContext _db;

        public GuestViewsController(TMSDbContext db)
        {
            _db = db;
        }

        // Actions View
        public IActionResult Home()
        {
            return View();
        }

        public IActionResult Books(bool menu, string command)
        {
            if (menu)
            {
                booksList = JsonConvert.DeserializeObject<List<BooksDB>>(command);
            }
            else
            {
                booksList = _db.DbBooks.OrderBy(x => x.Title).ToList();
            }
            return View(booksList);
        }
    }
}

TMS/Areas/User/Controllers/CartActionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System.Data;
using System.Security.Claims;
using TMS.Data;
using TMS.Models;
using TMS.Roles;

namespace TMS.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]

    public class CartActionsController : Controller
    {
        public List<TheShoppingCart> cartList = new List<TheShoppingCart>();
        public List<TheShoppingCart> cartList2 = new List<TheShoppingCart>();
        public List<UserHistory> historyList = new List<UserHistory>();

        // DB & UserManager
        private readonly UserManager<UserDB> _userManager;
        private readonly TMSDbContext _db;

        public CartActionsController
        (
            TMSDbContext db,
            UserManager<UserDB> userManager
        )
        {
            _db = db;
            _userManager = userManager;
        }

        //Views
        public IActionResult ShoppingCart()
        {
            var userclaim = (ClaimsIdentity)User.Identity;
            var userId = userclaim.FindFirst(ClaimTypes.NameIdentifier);

            cartList = _db.DbCart.Where(x => x.TheUserId == userId.Value).ToList();
            return View(cartList);
        }

        public IActionResult History()
        {
            if (User.IsInRole(TheRoles._Admin))
            {
                historyList = _db.DbHistory.ToList();
                return View(historyList);
            }
            else
            {
                var userclaim = (ClaimsIdentity)User.Identity;
                var userId = userclaim.FindFirst(ClaimTypes.NameIdentifier);

                historyList = _db.DbHistory.Where(x => x.TheUserId == userId.Value).ToList();
                return View(historyList);
            }
        }

        //Actions
        public IActionResult AddNow(int id)
        {
            var userclaim = (ClaimsIdentity)User.Identity;
            var userId = userclaim.FindFirst(ClaimTypes.NameIdentifier);

            var added = _db.DbBooks.Find(id);
            var check = _db.DbCart.Where(x => x.TheUserId == userId.Value).FirstOrDefault(y => y.BookId == added.Id);

            if (added.Quantity <= 0)
            {
                TempData["Info"] = "No more books available.";
                return RedirectToAction("Books", "GuestViews", new { area = "Guest" });
            }
            else if (check == null)
            {
                TheShoppingCart cart = new TheShoppingCart()
                {
                    BookId = added.Id,
                    TheUserId = userId.Value,
                    Title = added.Title,
                    Author = added.Author,
                    Quantity = 1,
                    Price = added.Price
                };
                _db.DbCart.Add(cart);
                _db.SaveChanges();
            }
            else
            {
                TempData["Info"] = "Already added.";
                return RedirectToAction("Books", "GuestViews", new { area = "Guest" });
            }

            return RedirectToAction("ShoppingCart");
        }

        public IActionResult Plus(int id)
        {
            var plus = _db.DbCart.Find(id);
            var check = _db.DbBooks.FirstOrDefault(x => x.Id == plus.BookId);

            if (plus.Quantity < check.Quantity)
            {
                plus.Quantity += 1;
                plus.Price = check.Price * plus.Quantity;
                _db.SaveChanges();
            }
            else
            {
                TempData["Info1"] = "No more books available";
            }

            return RedirectToAction("ShoppingCart");
        }

        public IActionResult Minus(int id)
        {
            var minus = _db.DbCart.Find(id);
            var check = _db.DbBooks.FirstOrDefault(x => x.Id == minus.BookId);

            minus.Quantity -= 1;

            if (minus.Quantity == 0)
            {
                _db.DbCart.Remove(minus);
            }
            else
            {
                minus.Price = minus.Price - check.Price;
            }

            _db.SaveChanges();
            return RedirectToAction("ShoppingCart");
        }

        public IActionResult Delete(int id)
        {
            var todelete = _db.DbCart.Find(id);

            _db.DbCart.Remove(todelete);
            _db.SaveChanges();
            return RedirectToAction("ShoppingCart");
        }

        public async Task<IActionResult> Order()
        {
            var userclaim = (ClaimsIdentity)User.Identity;
            var userId = userclaim.FindFirst(ClaimTypes.NameIdentifier);

            var user = await _userManager.GetUserAsync(User);

            if (user.Name == null || user.Location == null || user.Address == null || user.PhoneNr == null || user.CreditCard == null)
            {
                TempData["Info"] = "You must edit your info first.";
                return LocalRedirect("/Identity/Account/Manage/EditInfo");
            }
            else
            {
                cartList2 = _db.DbCart.Where(x => x.TheUserId == userId.Value).ToList();

                if (cartList2.Count == 0)
                {
                    TempData["Info1"] = "Your order is empty";
                    return RedirectToAction("ShoppingCart");
                }

                foreach (var orderedItem in cartList2)
                {
                    var manage = _db.DbBooks.FirstOrDefault(x => x.Id == orderedItem.BookId);
                    var check = manage.Quantity - orderedItem.Quantity;

                    if (check < 0)
                    {
                        TempData["Info2"] = "Some books must have run out of stock.";
                        return RedirectToAction("ShoppingCart");
                    }
                    else
                    {
                        UserHistory stored = new UserHistory()
                        {
                            TheUserId = orderedItem.TheUserId,
                            Title = orderedItem.Title,
                            Author = orderedItem.Author,
                            Quantity = orderedItem.Quantity,
                            Price = orderedItem.Price,
                            OrderTime = DateTime.Now,
                            Name = user.Name
                        };
                        _db.DbHistory.Add(stored);
                        _db.DbCart.Remove(orderedItem);

                        manage.Quantity = manage.Quantity - orderedItem.Quantity;

                        _db.SaveChanges();
                    }
                }

                TempData["Info"] = "Your order was successful!";
                return RedirectToAction("History");
            }
        }
    }
}

TMS/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TMS.Data;
using TMS.Models;

namespace TMS.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        public List<TheShoppingCart> cartList = new List<TheShoppingCart>();

        private readonly TMSDbContext _db;

        public ShoppingCartViewComponent(TMSDbContext db)
        {
            _db = db;

        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userclaim = (ClaimsIdentity)User.Identity;
            var userId = userclaim.FindFirst(ClaimTypes.NameIdentifier);

            if (userId == null)
            {
                return View("Default", false);
            }

            cartList = _db.DbCart.Where(x => x.TheUserId == userId.Value).ToList();

            if (cartList == null)
            {
                return View("Default", false);
            }

            if (cartList.Count > 0)
            {
                return View("Default", true);
            }
            else
            {
                return View("Default", false);
            }
        }
    }
}

TMS/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using TMS.Roles;

@inject SignInManager<UserDB> SignInManager
@inject UserManager<UserDB> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        * {
            padding: 0;
            margin: 0;
        }

        body {
            background-image: url('/Images/oldbackground.jpg');
            background-repeat: no-repeat;
            background-size: cover;
            background-attachment: fixed;
        }

        header {
            position: fixed;
            width: 100%;
            z-index: 1;
        }

        @@font-face {
            font-family: 'White Storm';
            src: url('/Fonts/White Storm.otf')
        }

        .navbar {
            list-style-type: none;
            padding: 13px;
            overflow: hidden;
            background-image: url('/Images/background.jfif');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 10%;
        }

        .navlink {
            float: left;
            color: #3a2613;
            padding: 9px;
            font-size: 30px;
            font-family: 'White Storm';
            text-decoration: none;
        }

            .navlink:hover {
                transform: scale(1.2);
                color: #ad7138;
            }

            .navlink:active {
                color: black;
            }

    </style>

    <link rel="stylesheet" href="~/TMS.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>

<body>

    <header>
        <ul class="navbar">
            <li>
                <a class="navlink" asp-area="Guest" asp-controller="GuestViews" asp-action="Home">Home</a>
            </li>
            <li>
                <a class="navlink" asp-area="Guest" asp-controller="GuestViews" asp-action="Books">Books</a>
            </li>

            @if (User.IsInRole(TheRoles._Admin))
            {
                <li>
                    <a class="navlink" asp-area="Admin" asp-controller="TMS" asp-action="Manage">Manage</a>
                </li>
            }

            @await Component.InvokeAsync("ShoppingCart")

            @if (User.IsInRole(TheRoles._Admin))
            {
                <li>
                    <a class="navlink" asp-area="User" asp-controller="CartActions" asp-action="History">History</a>
                </li>
            }

            @if (SignInManager.IsSignedIn(User))
            {
                <li style="float: right;">
                    <form asp-area="Identity" asp-page="/Account/Logout" method="post">
                        <button type="submit" class="navlink" style="background:none; border:none; cursor: pointer;">Log out</button>
                    </form>
                </li>
                <li style="float: right;">
                    <a class="navlink" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage"><i class="fa fa-solid fa-user"></i> @UserManager.GetUserName(User)</a>
                </li>
            }
            else
            {
                <li style="float: right;">
                    <a class="navlink" asp-area="Identity" asp-page="/Account/Register">Register</a>
                </li>
                <li style="float: right;">
                    <a class="navlink" asp-area="Identity" asp-page="/Account/Login">Log in</a>
                </li>
            }
        </ul>

    </header>
    <p style="padding-bottom: 90px;"></p>

    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer style="padding: 20px;">
    </footer>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>