TMS/Areas/Guest/Controllers/GuestViewsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TMS.Data;
using TMS.Models;

namespace TMS.Areas.Guest.Controllers
{
    [Area("Guest")]

    public class GuestViewsController : Controller
    {
        public List<BooksDB> booksList = new List<BooksDB>();

        //DB
        private readonly TMSDbContext _db;

        public GuestViewsController(TMSDbContext db)
        {
            _db = db;
        }

        // Actions View
        public IActionResult Home()
        {
            return View();
        }

        public IActionResult Books(bool menu, string command)
        {
            if (menu)
            {
                booksList = JsonConvert.DeserializeObject<List<BooksDB>>(command);
            }
            else
            {
                booksList = _db.DbBooks.OrderBy(x => x.Title).ToList();
            }
            return View(booksList);
        }
    }
}

TMS/Areas/Guest/Controllers/OperationsController.cs
using Microsoft.AspNetCore.Mvc;
using TMS.Models;
using TMS.Data;
using Newtonsoft.Json;

namespace TMS.Areas.Guest.Controllers
{
    [Area("Guest")]

    public class OperationsController : Controller
    {
        public List<BooksDB> booksList2 = new List<BooksDB>();

        // DB 
        private readonly TMSDbContext _db;

        public OperationsController(TMSDbContext db)
        {
            _db = db;
        }

        //Actions Sort/Category
        public IActionResult Sort(string sorting)
        {
            switch (sorting)
            {
                case "Name A-Z":
                    return RedirectToAction("BooksMenu", new { sorter = 1 });
                    break;
                case "Name Z-A":
                    return RedirectToAction("BooksMenu", new { sorter = 2 });
                    break;
                case "Price <":
                    return RedirectToAction("BooksMenu", new { sorter = 3 });
                    break;
                case "Price >":
                    return RedirectToAction("BooksMenu", new { sorter = 4 });
                    break;
                default:
                    return RedirectToAction("BooksMenu");
                    break;
            }
        }

        public IActionResult Category(string categorizing)
        {
            switch (categorizing)
            {
                case "Fantasy":
                    return RedirectToAction("BooksMenu", new { genre = "Fantasy" });
                    break;
                case "Adventure":
                    return RedirectToAction("BooksMenu", new { genre = "Adventure" });
                    break;
                case "Horror":
                    return RedirectToAction("BooksMenu", new { genre = "Horror" });
                    break;
                case "Drama":
                    return RedirectToAction("BooksMenu", new { genre = "Drama" });
                    break;
                case "Comedy":
                    return RedirectToAction("BooksMenu", new { genre = "Comedy" });
                    break;
                case "Dystopian":
                    return RedirectToAction("BooksMenu", new { genre = "Dystopian" });
                    break;
                case "Political":
                    return RedirectToAction("BooksMenu", new { genre = "Political" });
                    break;
                case "Science Fiction":
                    return RedirectToAction("BooksMenu", new { genre = "Science Fiction" });
                    break;
                case "History":
                    return RedirectToAction("BooksMenu", new { genre = "History" });
                    break;
                case "Romance":
                    return RedirectToAction("BooksMenu", new { genre = "Romance" });
                    break;
                default:
                    return RedirectToAction("BooksMenu");
                    break;
            }
        }

        public IActionResult BooksMenu(int sorter, string genre)
        {
            booksList2 = _db.DbBooks.Where(x => x.Genre1 == genre || x.Genre2 == genre).ToList();

            if (sorter == 1)
            {
                booksList2 = _db.DbBooks.OrderBy(x => x.Title).ToList();
            }
            else if (sorter == 2)
            {
                booksList2 = _db.DbBooks.OrderByDescending(x => x.Title).ToList();
            }
            else if (sorter == 3)
            {
                booksList2 = _db.DbBooks.OrderBy(x => x.Price).ToList();
            }
            else if (sorter == 4)
            {
                booksList2 = _db.DbBooks.OrderByDescending(x => x.Price).ToList();
            }

            return RedirectToAction("Books", "GuestViews", new { menu = true, command = JsonConvert.SerializeObject(booksList2.ToList()) });
        }
    }
}

TMS/Areas/User/Controllers/CartActionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System.Data;
using System.Security.Claims;
using TMS.Data;
using TMS.Models;
using TMS.Roles;

namespace TMS.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]

    public class CartActionsController : Controller
    {
        public List<TheShoppingCart> cartList = new List<TheShoppingCart>();
        public List<TheShoppingCart> cartList2 = new List<TheShoppingCart>();
        public List<UserHistory> historyList = new List<UserHistory>();

        // DB & UserManager
        private readonly UserManager<UserDB> _userManager;
        private readonly TMSDbContext _db;

        public CartActionsController
        (
            TMSDbContext db,
            UserManager<UserDB> userManager
        )
        {
            _db = db;
            _userManager = userManager;
        }

        //Views
        public IActionResult ShoppingCart()
        {
            var userclaim = (ClaimsIdentity)User.Identity;
            var userId = userclaim.FindFirst(ClaimTypes.NameIdentifier);

            cartList = _db.DbCart.Where(x => x.TheUserId == userId.Value).ToList();
            return View(cartList);
        }

        public IActionResult History()
        {
            if (User.IsInRole(TheRoles._Admin))
            {
                historyList = _db.DbHistory.ToList();
                return View(historyList);
            }
            else
            {
                var userclaim = (ClaimsIdentity)User.Identity;
                var userId = userclaim.FindFirst(ClaimTypes.NameIdentifier);

                historyList = _db.DbHistory.Where(x => x.TheUserId == userId.Value).ToList();
                return View(historyList);
            }
        }

        //Actions
        public IActionResult AddNow(int id)
        {
            var userclaim = (ClaimsIdentity)User.Identity;
            var userId = userclaim.FindFirst(ClaimTypes.NameIdentifier);

            var added = _db.DbBooks.Find(id);
            var check = _db.DbCart.Where(x => x.TheUserId == userId.Value).FirstOrDefault(y => y.BookId == added.Id);

            if (added.Quantity <= 0)
            {
                TempData["Info"] = "No more books available.";
                return RedirectToAction("Books", "GuestViews", new { area = "Guest" });
            }
            else if (check == null)
            {
                TheShoppingCart cart = new TheShoppingCart()
                {
                    BookId = added.Id,
                    TheUserId = userId.Value,
                    Title = added.Title,
                    Author = added.Author,
                    Quantity = 1,
                    Price = added.Price
                };
                _db.DbCart.Add(cart);
                _db.SaveChanges();
            }
            else
            {
                TempData["Info"] = "Already added.";
                return RedirectToAction("Books", "GuestViews", new { area = "Guest" });
            }

            return RedirectToAction("ShoppingCart");
        }

        public IActionResult Plus(int id)
        {
            var plus = _db.DbCart.Find(id);
            var check = _db.DbBooks.FirstOrDefault(x => x.Id == plus.BookId);

            if (plus.Quantity < check.Quantity)
            {
                plus.Quantity += 1;
                plus.Price = check.Price * plus.Quantity;
                _db.SaveChanges();
            }
            else
            {
                TempData["Info1"] = "No more books available";
            }

            return RedirectToAction("ShoppingCart");
        }

        public IActionResult Minus(int id)
        {
            var minus = _db.DbCart.Find(id);
            var check = _db.DbBooks.FirstOrDefault(x => x.Id == minus.BookId);

            minus.Quantity -= 1;

            if (minus.Quantity == 0)
            {
                _db.DbCart.Remove(minus);
            }
            else
            {
                minus.Price = minus.Price - check.Price;
            }

            _db.SaveChanges();
            return RedirectToAction("ShoppingCart");
        }

        public IActionResult Delete(int id)
        {
            var todelete = _db.DbCart.Find(id);

            _db.DbCart.Remove(todelete);
            _db.SaveChanges();
            return RedirectToAction("ShoppingCart");
        }

        public async Task<IActionResult> Order()
        {
            var userclaim = (ClaimsIdentity)User.Identity;
            var userId = userclaim.FindFirst(ClaimTypes.NameIdentifier);

            var user = await _userManager.GetUserAsync(User);

            if (user.Name == null || user.Location == null || user.Address == null || user.PhoneNr == null || user.CreditCard == null)
            {
                TempData["Info"] = "You must edit your info first.";
                return LocalRedirect("/Identity/Account/Manage/EditInfo");
            }
            else
            {
                cartList2 = _db.DbCart.Where(x => x.TheUserId == userId.Value).ToList();

                if (cartList2.Count == 0)
                {
                    TempData["Info1"] = "Your order is empty";
                    return RedirectToAction("ShoppingCart");
                }

                foreach (var orderedItem in cartList2)
                {
                    var manage = _db.DbBooks.FirstOrDefault(x => x.Id == orderedItem.BookId);
                    var check = manage.Quantity - orderedItem.Quantity;

                    if (check < 0)
                    {
                        TempData["Info2"] = "Some books must have run out of stock.";
                        return RedirectToAction("ShoppingCart");
                    }
                    else
                    {
                        UserHistory stored = new UserHistory()
                        {
                            TheUserId = orderedItem.TheUserId,
                            Title = orderedItem.Title,
                            Author = orderedItem.Author,
                            Quantity = orderedItem.Quantity,
                            Price = orderedItem.Price,
                            OrderTime = DateTime.Now,
                            Name = user.Name
                        };
                        _db.DbHistory.Add(stored);
                        _db.DbCart.Remove(orderedItem);

                        manage.Quantity = manage.Quantity - orderedItem.Quantity;

                        _db.SaveChanges();
                    }
                }

                TempData["Info"] = "Your order was successful!";
                return RedirectToAction("History");
            }
        }
    }
}

TMS/Areas/Guest/Views/GuestViews/Books.cshtml
@model List<BooksDB>

<html lang="en">
<head>
    <title>@ViewData["Title"] The Magic Shelf - Books</title>

    <style>
        .page {
            margin-left: 50px;
            margin-right: 150px;
            display: block;
        }

        .title {
            font-family: 'White Storm';
            font-size: 70px;
            margin-left: 300px;
        }

        .title2 {
            font-family: 'White Storm';
            font-size: 40px;
            color: #3a2613;
        }

        .temp {
            font-family: 'White Storm';
            font-size: 40px;
            margin-left: 465px;
            color: #cc3300;
        }

        .border {
            border: 7px solid #4d2600;
            border-radius: 12px;
            padding: 25px;
            margin: 15px;
            width: 20%;
            height: 510px;
            float: left;
            text-align: center;
            position: relative;
        }

        .borderbtn {
            left: 110px;
            top: 480px;
            position: absolute;
        }

        img {
            width: 200px;
            height: 300px;
            padding: 20px;
        }

            img:hover {
                opacity: 0.5;
            }

        .button {
            border: 3px solid #3a2613;
            background-color: #ffdf80;
            padding: 5px;
            font-family: 'White Storm';
            color: #3a2613;
            font-size: 25px;
            cursor: pointer;
        }

            .button:hover {
                opacity: 0.7;
            }

        .rightMenu {
            position: fixed;
            right: 0;
            height: 100%;
            width: 20%;
            margin-top: -17.8px;
            text-align: center;
            background-image: url('/Images/background2.jfif');
            background-repeat: no-repeat;
            background-size: 100% 100%;
            padding: 15px;
        }
    </style>

</head>

<body>

    <nav class="rightMenu">
        <div style="padding-bottom: 30px;">
            <form>
                <label for="quicksearch"><h3 class="title2">Quick search:</h3></label>
                <input type="text" id="quicksearch"></input><br />
                <input type="button" class="button" style="font-size: 20px; margin-top: 3px;" value="Search" onclick="search(document.getElementById('quicksearch').value)">

            </form>
        </div>

        <script>
            function search(string) {
                window.find(string);
            }
        </script>

        <div style="padding-bottom: 30px;">
            <form asp-controller="Operations" asp-action="Sort">
                <h3 class="title2">Sort by:</h3>

                <input type="radio" name="sorting" value="Name A-Z" />
                <label for="Name A-Z">Name A-Z</label><br />
                <input type="radio" name="sorting" value="Name Z-A" />
                <label for="Name Z-A">Name Z-A</label><br />
                <input type="radio" name="sorting" value="Price <" />
                <label for="Price <">Price < </label><br />
                <input type="radio" name="sorting" value="Price >" />
                <label for="Price >">Price ></label><br />

                <input type="submit" class="button" style="font-size: 20px; margin-top: 5px; width: 60px;" value="Sort">
            </form>
        </div>

        <div>
            <form asp-controller="Operations" asp-action="Category">
                <h3 class="title2">Category:</h3>

                <input type="radio" name="categorizing" value="Adventure" />
                <label for="Adventure">Adventure</label><br />
                <input type="radio" name="categorizing" value="Comedy" />
                <label for="Comedy">Comedy</label><br />
                <input type="radio" name="categorizing" value="Drama" />
                <label for="Drama">Drama</label><br />
                <input type="radio" name="categorizing" value="Dystopian" />
                <label for="Dystopian">Dystopian</label><br />
                <input type="radio" name="categorizing" value="Fantasy" />
                <label for="Fantasy">Fantasy</label><br />
                <input type="radio" name="categorizing" value="History" />
                <label for="History">History</label><br />
                <input type="radio" name="categorizing" value="Horror" />
                <label for="Horror">Horror</label><br />
                <input type="radio" name="categorizing" value="Political" />
                <label for="Political">Political</label><br />
                <input type="radio" name="categorizing" value="Romance" />
                <label for="Romance">Romance</label><br />
                <input type="radio" name="categorizing" value="Science Fiction" />
                <label for="Science Fiction">Science Fiction</label><br />

                <input type="submit" class="button" style="font-size: 20px; margin-top: 5px; width: 60px;" value="Select">
            </form>
        </div>
    </nav>

    <h1 class="title">Feel free to browse our store</h1>

    <span class="temp">@TempData["Info"]</span>

    @{
        bool x;
    }
    <div class="page">

        @foreach (var i in Model)
        {
            <div class="border">
                <img src="@i.Image" />
                <h2>@i.Title,</h2>
                <h3>@i.Author</h3>
                <h4>
                    <i>
                        @i.Genre1 @if (i.Genre1 != i.Genre2)
                        {
                            <i>, </i> @i.Genre2
                        }
                    </i>
                </h4><br />
                <footer class="borderbtn">
                    <i>@i.Price lei</i><br /><br />
                    <a class="button" asp-area="User" asp-controller="CartActions" asp-action="AddNow" asp-route-id=@i.Id>Add now!</a>
                </footer>
            </div>
        }

    </div>

</body>
</html>

TMS/Areas/Guest/Views/GuestViews/Home.cshtml
<html lang="en">
<head>
    <title>@ViewData["Title"] The Magic Shelf - Home</title>

    <style>
        .home {
            font-family: 'White Storm';
            font-size: 50px;
            text-align: center;
        }

        .links {
            color: #ad7138;
            text-decoration: none;
            display: inline-block;
        }

            .links:hover {
                transform: scale(1.1);
                color: #c78a52;
                text-decoration: underline;
            }

            .links:active {
                color: black;
                text-decoration: none;
            }

    </style>
</head>

<body>

    <h2 class="home" style="font-size:40px; color: #009900;;">@TempData["Deleted"]</h2>

    <div class="home">
        <h1>Welcome to</h1>
        <h1 style="font-size: 150px;">The Magic Shelf</h1>
        <br />

        <div style="color: #3a2613;">
            <p>Check out our collection of <a class="links" asp-area="Guest" asp-controller="GuestViews" asp-action="Books">books</a>.</p>
            <p>Don't forget to <a class="links" asp-area="Identity" asp-page="/Account/Login">log in</a> and</p>
            <p>order your favourites.</p>
            <p>If you don't have an account, <a class="links" asp-area="Identity" asp-page="/Account/Register">register now!</a></p>
        </div>

    </div>

</body>
</html>